### PR TITLE
Update docs to reflect new Premium virtual group

### PR DESCRIPTION
**Pull request by ElliottLMz**

### CODE REVIEW

**Comment by evaera** [comment]
do we need to remove the old ones? i think we probaby should

**Comment by ElliottLMz** [comment]
At present, I don't believe BC has been fully removed from the platform. Although I can see removing the BC virtual groups _from the docs_.

**Comment by evaera** [comment]
the commit removed them so just remove them from docs

**Comment by PhoenixShay** [comment]
NBC still exists

**Comment by ElliottLMz** [comment]
Oversight on my part. The NBC virtual group should probably be renamed as it's slightly misleading.

**Comment by PhoenixShay** [comment]
I believe Roblox still refers to it as NBC, so I stuck with it

**Pull request merged**
