### PR TITLE
Update client.json

### PR DESCRIPTION
**Pull request by JavaOldMan**

### CODE REVIEW

**Comment by HypheX** [comment]
What... why are you leaking your bot token. And why are you pushing this.

**Comment by One-Nub** [comment]
Considering this is their first pull request, I'm guessing they didn't know what making a pull request did? maybe....
regardless, that token should be regenerated (and not pushed to github in the first place)

**Comment by HypheX** [comment]
Probably. I tried to contact the user in Discord about how they just leaked their bot token, and should regenerate it, but to no avail, I just hope they read this.

**Comment by JavaOldMan** [comment]
LOL sorry lads, it's not a real token.

**Comment by JavaOldMan** [comment]
> Probably. I tried to contact the user in Discord about how they just leaked their bot token, and should regenerate it, but to no avail, I just hope they read this.

thanks for caring! but yeah its not real

**Pull request closed without merging**
