### PR TITLE
Give contributors more recognition

### PR DESCRIPTION
**Pull request by suufi**
contributors deserve more recognition so i added a thing that says `[CONTRIBUTOR]` right after their username when people do !whois

### CODE REVIEW

**Comment by evaera** [comment]
Hard coding user IDs in code is a bad idea. Change doesn't follow the code style guide. I don't want to change the username field because that could make it hard to copy.

Maybe this could be added a new field in the embed, like "User Tags" or "RoVer Badges" or something... I'm not sure. As far as storing the IDs, we could put that in ./src/contributors.json

**Comment by suufi** [comment]
RoVer Badges sounds more cool. I think we could also put things like
DevForum member in there as well considering most servers don't give out
that role.

**Comment by PhoenixShay** [comment]
I think it would be better to have an endpoint on the verify.eryn.io API that has a list of the discord IDs of people with the contributor rank in the support server, instead of having a json file or anything hardcoded.

**Comment by evaera** [comment]
Maybe, except verify.eryn.io and RoVer are intended to be entirely separate entities

**Pull request merged**
