### PR TITLE
Fetch bot member in guild when .me is null

### PR DESCRIPTION
**Pull request by Wolftallemo**
Currently we've been seeing the verifiedrole command failing in some servers when .me is null, the notverifiedrole command was fixed as well in case that comes up.

### CODE REVIEW

**Comment by Rythian2277** [comment]
After looking at the DiscordServer.js file, there is a function made which compares rank positions, could this be used for ease of updating in future? (I missed it within my own code aswell Fml)

**Comment by Wolftallemo** [comment]
Well yes, however it also checks for the bot's ability to manage roles (which may or may not be a good thing depending on how you view it)

**Comment by Rythian2277** [comment]
It would prevent people from trying to bind when it doesn't have permission aswell, extra benefit

**Comment by Wolftallemo** [comment]
Yes, although we won't be able to communicate the specific error unless the checks are added elsewhere to determine what condition failed, but a general error might suffice

**Review by Rythian2277 — APPROVED** [review]
We're seeing this issue more and more recently, this method currently works and we can review it down the line to optimise the functionality.

**Pull request merged**
