### PR TITLE
Fix final possibly-soon-to-be deprecated endpoint

### PR DESCRIPTION
**Pull request by Wolftallemo**
Found a stray remaining old endpoint in discordmember

### CODE REVIEW

**Comment by TheCoolOne123** [comment]
Lmao, i fixed that in my pr. 🤣

**Comment by TheCoolOne123** [comment]
Gotta admit, you gotta love roblox for something. But it ain't their api

**Comment by Wolftallemo** [comment]
Yep, sadly you got skipped over on that.

________________________________

**Comment by TheCoolOne123** [comment]
😭

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Review by Rythian2277 — APPROVED** [review]
👍

**Pull request merged**
