### PR TITLE
Add DevForumGroup VirtualGroup

### PR DESCRIPTION
**Pull request by RealSimplyData**
Allows users to dynamically bind any DevForum Group.
This PR also changes how bindings are made; Strings can now be used for bindings, but only if its for a virtual group, if it's a roblox group, then it will only allow numbers); It also no longer allows NaN bindings (which it did before)

### CODE REVIEW

**Comment by RealSimplyData** [comment]
No clue why `package-lock.json` updated, hoping that won't cause any major issues (Github Workspaces installed `node_modules` for me automatically, so I was unsure that got updated).

**Comment by Rythian2277** [comment]
Overwritten the edits to package-lock.json

**Review by Wolftallemo — APPROVED** [review]

**Comment by Wolftallemo** [comment]
While a warning would be preferable should someone try to bind a NaN rank, it's ultimately not the highest priority so it can probably be included in a separate pr (as previously you could set a NaN binding which would also delete the old bind) ~~and since we're here we should take a look at #291 again~~

**Comment by Rythian2277** [comment]
We would need to define which VG's require an argument and those that do not, for example, the PostApproval group doesn't take any arguments so NaN is a valid thing for it while Asset requires the AssetID. Honestly in my opinion an overhaul on virtualgroups and how they work may be required in a future official maintenance PR.

**Comment by RealSimplyData** [comment]
Noticed that Virtual Groups always get their arguments as a string (oopsy from me), should be fixed with https://github.com/evaera/RoVer/pull/326/commits/945652eb04e08a9834a3cbb397943eb9a5c8fdf0.

**Comment by Rythian2277** [comment]
@RealSimplyData ETA on finishing the rank argument checks?

**Comment by RealSimplyData** [comment]
Working on it on the side while I finish up some personal things. ETA end of the week if everything goes well.

**Comment by Wolftallemo** [comment]
Is all going well so far? It's been a while since we've heard anything about this

**Comment by Wolftallemo** [comment]
Please open another pr when you are ready as this one is stale

**Pull request closed without merging**
