### PR TITLE
Updated old endpoints from api.roblox.com to groups. and user.

### PR DESCRIPTION
**Pull request by TheCoolOne123**
Roblox loves to (most of the time) change their endpoints breaking almost any bots that use them. 
See: https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/37?u=superstefano4

I've changed the bot so it uses the new endpoints that roblox uses

### CODE REVIEW

**Comment by Rythian2277** [comment]
Similar patches to #304, does not update `!whois` command though.

**Comment by TheCoolOne123** [comment]
Didn't someone fix this in an different pr?

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by Wolftallemo** [comment]
> 
> 
> Similar patches to #304, does not update `!whois` command though.

Yeah that was fixed in #296

**Comment by Rythian2277** [comment]
Duplicates fixes implemented by #304.

**Pull request closed without merging**
